### ISSUE TITLE
test.pl generates warning as of upcoming perl-5.37.9

### ISSUE THREAD

**Issue by jkeenan** [jonathanstowe/Term-Cap#14]
In https://github.com/jonathanstowe/Term-Cap/commit/c280c2f44a25fea4302d8dd7e917dc14b82fb5b8, an instance of `Test::More::isn't()` in `test.pl` was replaced with `isnt()` in anticipation of changes in Perl 5.  This change, however, has not yet been released to CPAN.

Those changes in `perl` have now arrived.
```
commit 7e2d91e6d3a09e2ebb61242bb18ff95d30d9560d
Author: Tony Cook <tony@develop-help.com>
Date:   Wed Dec 7 16:17:45 2022 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Tue Feb 7 10:37:30 2023 +1100

    toke.c: deprecation warning for ' as a package separator
    
    First stage of RFC 0015.
    
    This also changes the warning for ' as package separator in
    quoted strings to also be a deprecation warning.
```
As a consequence, deprecation warnings are now showing up for Term-Cap when we test the core distribution, run Test::Smoke, etc.
```
cpan/Term-Cap/test ............................................... Old package separator "'" deprecated at test.pl line 124.
ok
```
Could we get a new CPAN release that addresses this problem?

Thank you very much.
Jim Keenan

**Comment by demerphq** [comment]
Note this was already fixed 8 months ago, so I think all you need to do is roll a new release.

**Comment by jonathanstowe** [comment]
Yep I'll release it tomorrow.

**Comment by demerphq** [comment]
Thanks. Looking forward to synching it into core. :-)

**Comment by jonathanstowe** [comment]
I've released that to PAUSE as 1.18, similarly tagged here if that's more useful.

**Comment by demerphq** [comment]
Thanks, much obliged

**Comment by demerphq** [comment]
This was merged into core today. Thanks again!

**Comment by jonathanstowe** [comment]
To be honest I'm surprised that anyone still uses it and it hasn't been ridded from the core.  It's years since I've seen an OS that installed a `termcap` by default, and the "_fallback_" entry is frankly useless.

**Comment by demerphq** [comment]
That we are fixing it, or care when we break it, is not an indication it is being used. :-)

I am sure the perl folks would welcome the idea of removing it if you think is the best thing. We go into robot mode as far as stuff like this goes. We dont really consider if something being used, we just care that it passes test and doesnt warn when we run tests. Same goes for BBC. I have had BBC reports for Acme modules that never worked in the first place and we debated what we should do (in the end we said "wont fix"). Very conservative we are as far as stuff like this goes.

You are likely the best placed person to begin this conversation tho. I know nothing about it, I am just in workhorse mode dealing with falll-out from deprecating apostrophe as a package separator, and other changes. (I cant count how many BBC fixes ive done in the last months.... Sigh.)

**Comment by pgnd** [comment]
> To be honest I'm surprised that anyone still uses it and it hasn't been ridded from the core. It's years since I've seen an OS that installed a `termcap` by default, and the "_fallback_" entry is frankly useless.

@jonathanstowe @demerphq   was there any further discussion/decision re: this mod on keeping in, or removing from, perl-core ?

**Comment by demerphq** [comment]
@pgnd not by me. I think it is up to @jonathanstowe to start that ball rolling.
