### ISSUE TITLE
Test failure in Term-Cap 1.16

### ISSUE THREAD

**Issue by steve-m-hay** [jonathanstowe/Term-Cap#3]
This pull request:

https://github.com/jonathanstowe/Term-Cap/pull/2

which was merged and released in Term-Cap-1.16 causes test failures on HP-UX as reported on CPAN RT here:

https://rt.cpan.org/Public/Bug/Display.html?id=96695

and also caused failures in two 'podlators' tests when it was merged into the perl core distribution, which resulted in that merge being undone:

http://perl5.git.perl.org/perl.git/commit/663bce880acdd4bee8f6d5b50dbb3fee75e1d0ec

I see in the comments at the end of the pull request that the author of the patch is no longer sure that it does the right thing.

Perhaps the change should be reverted until a proper fix for the original problem can be found?

**Comment by jonathanstowe** [comment]
Tricky to test on HP-UX for me.

Will take a look.

**Comment by jonathanstowe** [comment]
This should be fixed with 48a46448fafcba35094615adad869f942dd0801f if someone wants to test

**Comment by steve-m-hay** [comment]
I don't have HP-UX either, but since the logic is now equivalent (by De Morgan's laws) to what was in 1.15 I'm sure it's fine.

(Restoring the behaviour of 1.15 presumably reintroduces the bug that https://github.com/jonathanstowe/Term-Cap/pull/2 was trying to fix, but I guess that will have to be revisited as and when it comes up again since the author wasn't sure the patch did the right thing anyway: https://github.com/jonathanstowe/Term-Cap/pull/2#issuecomment-39442340)

**Comment by jonathanstowe** [comment]
I think the way I am going to play this is make an 1.17-RC1 release to solicit testing and see how it goes for a while before making a stable release.

**Comment by jonathanstowe** [comment]
While I am thinking about it, is there anyone able to explain what makes HP-UX different in regard to failing with this?  Some combination of no /etc/termcap and no infotocap or something I guess.

**Comment by jonathanstowe** [comment]
And in other news due to the kind and good offices of H.Merijn Brand I now have a HP-UX account to test this on

**Comment by jonathanstowe** [comment]
Hi,
I've released version 1.17.  Hopefully there won't be any further priblems.
