### ISSUE TITLE
Documentations uses indirect object syntax.

### ISSUE THREAD

**Issue by EvanCarroll** [jonathanstowe/Term-Cap#9]
> Outside of the file handle case, use of this syntax is discouraged as it can confuse the Perl interpreter. See below for more details.

I believe we should be switching,

    my $terminal = Tgetent Term::Cap { TERM => undef, OSPEED => $ospeed };
    my $termios = new POSIX::Termios;

to

    my $terminal = Term::Cap->Tgetent( { TERM => undef, OSPEED => $ospeed } );
    my $termios = POSIX::Termios->new();

**Comment by jonathanstowe** [comment]
Hi, that was actually fixed in 8c4e5d12 it just hasn't been released yet.
